In [1]:
import pandas as pd
import geopandas as gpd
from getpass import getpass
from urllib.parse import quote_plus
import matplotlib.pyplot as plt
import os
from PIL import Image
import folium
from folium import GeoJson

In [2]:
# Database connection info
host = "localhost"
database = "gis"
user = "moritz"
port = "25432"  # Specify the custom port here
password = getpass("Enter your password: ")

# URL-encode the password to handle special characters
encoded_password = quote_plus(password)

# Add the port in the connection string
connection_string = f"postgresql://{user}:{encoded_password}@{host}:{port}/{database}"

from sqlalchemy import create_engine

engine = create_engine(connection_string)

from sqlalchemy import inspect

# If you want to use %sql magic in Jupyter
%reload_ext sql
%sql $connection_string
%config SqlMagic.style = 'DEFAULT'

Enter your password:  ········

In [3]:
%%sql
SELECT table_name FROM information_schema.tables WHERE table_schema='public'

 * postgresql://moritz:***@localhost:25432/gis
28 rows affected.

[('planet_osm_polygon',),
 ('berlin',),
 ('planet_osm_point',),
 ('spatial_ref_sys',),
 ('geography_columns',),
 ('geometry_columns',),
 ('munich',),
 ('amsterdam',),
 ('global_streetscapes',),
 ('new_york',),
 ('paris',),
 ('raster_columns',),
 ('raster_overviews',),
 ('london',),
 ('tokyo',),
 ('sydney',),
 ('warsaw',),
 ('madrid',),
 ('global-streetscapes',),
 ('planet_osm_nodes',),
 ('planet_osm_ways',),
 ('planet_osm_rels',),
 ('cologne',),
 ('hamburg',),
 ('copenhagen',),
 ('osm2pgsql_properties',),
 ('planet_osm_roads',),
 ('planet_osm_line',)]

In [8]:
%%sql

SELECT name FROM planet_osm_point WHERE tourism = 'attraction' LIMIT 20;

 * postgresql://moritz:***@localhost:25432/gis
20 rows affected.

[('Summloch',),
 ('Auguste-Victoria Glocke',),
 ('Weiße Maulbeere',),
 ('Die Schuldenuhr Deutschlands',),
 ('Checkpoint Charlie',),
 ('Postblock Trabant',),
 ('Topographie des Terrors',),
 (None,),
 ('Wachturm',),
 ('Meisenbach Höfe',),
 ('Wasserfall',),
 ('Labyrintoom',),
 ('Wasserspiele',),
 ('Fontäne im Fennpfuhl',),
 ('Historischer Hafen Berlin',),
 ('Stadtbad Oderberger Straße',),
 ('Sowjetisches Ehrenmal',),
 ('Alte Fasanerie',),
 ('Luisenbad',),
 ('Flugsimulator Berlin',)]